### ISSUE TITLE
react-hook-form integration

### ISSUE THREAD

**Issue by francescortiz** [michaljanocko/schemawax#12]
I have been working in a form in react using `react-hook-form` and I tried to set up input resolver using `yup` and `zod`. Both were a pain. A simple operation that is receiving an string and casting it to another type is not possible with `zod` and seriously tedious in `yup`. Do you think that it is possible to use `schemawax` as a resolver for `react-hook-form`?

https://react-hook-form.com/api/useform#validationResolver

Thanks!

**Comment by michaljanocko** [comment]
Sorry for not responding earlier—**it should be possible!** I am not very big on React but I might look into this and share the results of my explorations.

**Comment by michaljanocko** [comment]
So I tried it out real quick and it is possible to validate the form with `schemawax`. However, it requires some boilerplate as the `react-hook-form` is not really friendly. For a simple use-case I actually suggest doing the stuff manually because `react-hook-form` doesn't make it that easy. With that said, it's entirely possible to validate forms with `schemawax`. You would just need to keep an object with validators for all fields and then you're ready to rock.

**Comment by francescortiz** [comment]
Thank you for taking your time to analyze it.
